blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: ğŸš€ Feature Request
    description: Suggest a new idea or product improvement
    file: feature_request.md
  - name: ğŸ› Bug Report
    description: Report something that isnâ€™t working as expected
    file: bug_report.md
